import { BaseSchema } from '@adonisjs/lucid/schema'

export default class extends BaseSchema {
  async up() {
    // Documents Affréteur (3)
    await this.db.table('document_types').insert([
      {
        code: 'CNI_AFFRETEUR',
        label_fr: "Carte Nationale d'Identité",
        label_en: 'National ID Card',
        description: "Carte d'identité nationale à jour du particulier affréteur",
        applicable_to: 'user',
        required_for_roles: '{affreteur}',
        required_for_vehicle_types: null,
        has_expiration: true,
        default_validity_days: 3650, // 10 ans
        file_format_restrictions: '{"allowed": ["pdf", "jpg", "jpeg", "png"], "max_size_mb": 5}',
        validation_rules: null,
        is_active: true,
        display_order: 1,
        created_at: this.now(),
        updated_at: this.now(),
      },
      {
        code: 'NIU_AFFRETEUR',
        label_fr: "Numéro d'Identification Unique",
        label_en: 'Unique Identification Number',
        description: 'NIU du particulier affréteur',
        applicable_to: 'user',
        required_for_roles: '{affreteur}',
        required_for_vehicle_types: null,
        has_expiration: false,
        default_validity_days: null,
        file_format_restrictions: '{"allowed": ["pdf", "jpg", "jpeg", "png"], "max_size_mb": 5}',
        validation_rules: null,
        is_active: true,
        display_order: 2,
        created_at: this.now(),
        updated_at: this.now(),
      },
      {
        code: 'PLAN_LOCALISATION_AFFRETEUR',
        label_fr: 'Plan de Localisation Résidence',
        label_en: 'Residence Location Plan',
        description: 'Plan de localisation de la résidence du particulier',
        applicable_to: 'user',
        required_for_roles: '{affreteur}',
        required_for_vehicle_types: null,
        has_expiration: false,
        default_validity_days: null,
        file_format_restrictions: '{"allowed": ["pdf", "jpg", "jpeg", "png"], "max_size_mb": 5}',
        validation_rules: null,
        is_active: true,
        display_order: 3,
        created_at: this.now(),
        updated_at: this.now(),
      },
    ])

    // Documents Transporteur (5)
    await this.db.table('document_types').insert([
      {
        code: 'REGISTRE_COMMERCE',
        label_fr: 'Registre de Commerce',
        label_en: 'Commercial Register',
        description: "Registre de commerce de l'entreprise de transport",
        applicable_to: 'user',
        required_for_roles: '{transporteur}',
        required_for_vehicle_types: null,
        has_expiration: true,
        default_validity_days: 365, // 1 an
        file_format_restrictions: '{"allowed": ["pdf"], "max_size_mb": 10}',
        validation_rules: null,
        is_active: true,
        display_order: 1,
        created_at: this.now(),
        updated_at: this.now(),
      },
      {
        code: 'NIU_TRANSPORTEUR',
        label_fr: 'NIU Entreprise',
        label_en: 'Company NIU',
        description: "Numéro d'Identification Unique de l'entreprise",
        applicable_to: 'user',
        required_for_roles: '{transporteur}',
        required_for_vehicle_types: null,
        has_expiration: false,
        default_validity_days: null,
        file_format_restrictions: '{"allowed": ["pdf", "jpg", "jpeg", "png"], "max_size_mb": 5}',
        validation_rules: null,
        is_active: true,
        display_order: 2,
        created_at: this.now(),
        updated_at: this.now(),
      },
      {
        code: 'ACF',
        label_fr: 'Attestation de Conformité Fiscale',
        label_en: 'Tax Compliance Certificate',
        description: "Attestation de conformité fiscale de l'entreprise",
        applicable_to: 'user',
        required_for_roles: '{transporteur}',
        required_for_vehicle_types: null,
        has_expiration: true,
        default_validity_days: 365, // 1 an
        file_format_restrictions: '{"allowed": ["pdf"], "max_size_mb": 5}',
        validation_rules: null,
        is_active: true,
        display_order: 3,
        created_at: this.now(),
        updated_at: this.now(),
      },
      {
        code: 'PLAN_LOCALISATION_TRANSPORTEUR',
        label_fr: 'Plan de Localisation Entreprise',
        label_en: 'Company Location Plan',
        description: "Plan de localisation du siège de l'entreprise",
        applicable_to: 'user',
        required_for_roles: '{transporteur}',
        required_for_vehicle_types: null,
        has_expiration: false,
        default_validity_days: null,
        file_format_restrictions: '{"allowed": ["pdf", "jpg", "jpeg", "png"], "max_size_mb": 5}',
        validation_rules: null,
        is_active: true,
        display_order: 4,
        created_at: this.now(),
        updated_at: this.now(),
      },
      {
        code: 'CNI_GERANT',
        label_fr: 'CNI du Gérant',
        label_en: 'Manager ID Card',
        description: "Carte nationale d'identité du gérant de l'entreprise",
        applicable_to: 'user',
        required_for_roles: '{transporteur}',
        required_for_vehicle_types: null,
        has_expiration: true,
        default_validity_days: 3650, // 10 ans
        file_format_restrictions: '{"allowed": ["pdf", "jpg", "jpeg", "png"], "max_size_mb": 5}',
        validation_rules: null,
        is_active: true,
        display_order: 5,
        created_at: this.now(),
        updated_at: this.now(),
      },
    ])

    // Documents Véhicule (17)
    await this.db.table('document_types').insert([
      {
        code: 'CARTE_GRISE_TRACTEUR',
        label_fr: 'Carte Grise Tracteur',
        label_en: 'Tractor Registration Card',
        description: 'Carte grise du tracteur routier',
        applicable_to: 'vehicle',
        required_for_roles: null,
        required_for_vehicle_types: '{truck,van}',
        has_expiration: false,
        default_validity_days: null,
        file_format_restrictions: '{"allowed": ["pdf", "jpg", "jpeg", "png"], "max_size_mb": 5}',
        validation_rules: null,
        is_active: true,
        display_order: 1,
        created_at: this.now(),
        updated_at: this.now(),
      },
      {
        code: 'CARTE_GRISE_REMORQUE',
        label_fr: 'Carte Grise Remorque',
        label_en: 'Trailer Registration Card',
        description: 'Carte grise de la remorque',
        applicable_to: 'vehicle',
        required_for_roles: null,
        required_for_vehicle_types: '{truck}',
        has_expiration: false,
        default_validity_days: null,
        file_format_restrictions: '{"allowed": ["pdf", "jpg", "jpeg", "png"], "max_size_mb": 5}',
        validation_rules: null,
        is_active: true,
        display_order: 2,
        created_at: this.now(),
        updated_at: this.now(),
      },
      {
        code: 'ASSURANCE_TRACTEUR',
        label_fr: 'Assurance Tracteur',
        label_en: 'Tractor Insurance',
        description: "Attestation d'assurance du tracteur",
        applicable_to: 'vehicle',
        required_for_roles: null,
        required_for_vehicle_types: '{truck,van,motorcycle,car}',
        has_expiration: true,
        default_validity_days: 365, // 1 an
        file_format_restrictions: '{"allowed": ["pdf"], "max_size_mb": 5}',
        validation_rules: null,
        is_active: true,
        display_order: 3,
        created_at: this.now(),
        updated_at: this.now(),
      },
      {
        code: 'ASSURANCE_REMORQUE',
        label_fr: 'Assurance Remorque',
        label_en: 'Trailer Insurance',
        description: "Attestation d'assurance de la remorque",
        applicable_to: 'vehicle',
        required_for_roles: null,
        required_for_vehicle_types: '{truck}',
        has_expiration: true,
        default_validity_days: 365, // 1 an
        file_format_restrictions: '{"allowed": ["pdf"], "max_size_mb": 5}',
        validation_rules: null,
        is_active: true,
        display_order: 4,
        created_at: this.now(),
        updated_at: this.now(),
      },
      {
        code: 'CARTE_BLEUE_TRACTEUR',
        label_fr: 'Carte Bleue Tracteur',
        label_en: 'Tractor Blue Card',
        description: 'Carte bleue du tracteur',
        applicable_to: 'vehicle',
        required_for_roles: null,
        required_for_vehicle_types: '{truck,van}',
        has_expiration: true,
        default_validity_days: 365,
        file_format_restrictions: '{"allowed": ["pdf", "jpg", "jpeg", "png"], "max_size_mb": 5}',
        validation_rules: null,
        is_active: true,
        display_order: 5,
        created_at: this.now(),
        updated_at: this.now(),
      },
      {
        code: 'CARTE_BLEUE_REMORQUE',
        label_fr: 'Carte Bleue Remorque',
        label_en: 'Trailer Blue Card',
        description: 'Carte bleue de la remorque',
        applicable_to: 'vehicle',
        required_for_roles: null,
        required_for_vehicle_types: '{truck}',
        has_expiration: true,
        default_validity_days: 365,
        file_format_restrictions: '{"allowed": ["pdf", "jpg", "jpeg", "png"], "max_size_mb": 5}',
        validation_rules: null,
        is_active: true,
        display_order: 6,
        created_at: this.now(),
        updated_at: this.now(),
      },
      {
        code: 'LICENCE_TRANSPORT',
        label_fr: 'Licence de Transport',
        label_en: 'Transport License',
        description: 'Licence de transport routier',
        applicable_to: 'vehicle',
        required_for_roles: null,
        required_for_vehicle_types: '{truck,van}',
        has_expiration: true,
        default_validity_days: 365,
        file_format_restrictions: '{"allowed": ["pdf"], "max_size_mb": 5}',
        validation_rules: null,
        is_active: true,
        display_order: 7,
        created_at: this.now(),
        updated_at: this.now(),
      },
      {
        code: 'AGREMENT_TRANSPORT',
        label_fr: 'Agrément de Transport',
        label_en: 'Transport Approval',
        description: 'Agrément de transport routier',
        applicable_to: 'vehicle',
        required_for_roles: null,
        required_for_vehicle_types: '{truck,van}',
        has_expiration: true,
        default_validity_days: 365,
        file_format_restrictions: '{"allowed": ["pdf"], "max_size_mb": 5}',
        validation_rules: null,
        is_active: true,
        display_order: 8,
        created_at: this.now(),
        updated_at: this.now(),
      },
      {
        code: 'CERTIFICAT_JAUGAGE',
        label_fr: 'Certificat de Jaugage',
        label_en: 'Gauging Certificate',
        description: 'Certificat de jaugage pour camion citerne',
        applicable_to: 'vehicle',
        required_for_roles: null,
        required_for_vehicle_types: '{truck}',
        has_expiration: true,
        default_validity_days: 365,
        file_format_restrictions: '{"allowed": ["pdf"], "max_size_mb": 5}',
        validation_rules: '{"conditional": "vehicle.metadata.is_citerne === true"}',
        is_active: true,
        display_order: 9,
        created_at: this.now(),
        updated_at: this.now(),
      },
      {
        code: 'PERMIS_CHAUFFEUR',
        label_fr: 'Permis de Conduire Chauffeur',
        label_en: 'Driver License',
        description: 'Permis de conduire du chauffeur assigné',
        applicable_to: 'vehicle',
        required_for_roles: null,
        required_for_vehicle_types: '{truck,van,motorcycle,car}',
        has_expiration: true,
        default_validity_days: 1825, // 5 ans
        file_format_restrictions: '{"allowed": ["pdf", "jpg", "jpeg", "png"], "max_size_mb": 5}',
        validation_rules: null,
        is_active: true,
        display_order: 10,
        created_at: this.now(),
        updated_at: this.now(),
      },
      {
        code: 'CARTE_ACCES_CHAUFFEUR',
        label_fr: "Carte d'Accès Chauffeur",
        label_en: 'Driver Access Card',
        description: "Carte d'accès pour chauffeur citerne",
        applicable_to: 'vehicle',
        required_for_roles: null,
        required_for_vehicle_types: '{truck}',
        has_expiration: true,
        default_validity_days: 365,
        file_format_restrictions: '{"allowed": ["pdf", "jpg", "jpeg", "png"], "max_size_mb": 5}',
        validation_rules: '{"conditional": "vehicle.metadata.is_citerne === true"}',
        is_active: true,
        display_order: 11,
        created_at: this.now(),
        updated_at: this.now(),
      },
      {
        code: 'ATTESTATION_CONDUITE_DEFENSIVE',
        label_fr: 'Attestation de Conduite Défensive',
        label_en: 'Defensive Driving Certificate',
        description: 'Attestation de formation à la conduite défensive',
        applicable_to: 'vehicle',
        required_for_roles: null,
        required_for_vehicle_types: '{truck,van}',
        has_expiration: true,
        default_validity_days: 730, // 2 ans
        file_format_restrictions: '{"allowed": ["pdf"], "max_size_mb": 5}',
        validation_rules: null,
        is_active: true,
        display_order: 12,
        created_at: this.now(),
        updated_at: this.now(),
      },
      {
        code: 'VISITE_TECHNIQUE_TRACTEUR',
        label_fr: 'Visite Technique Tracteur',
        label_en: 'Tractor Technical Inspection',
        description: 'Certificat de visite technique du tracteur',
        applicable_to: 'vehicle',
        required_for_roles: null,
        required_for_vehicle_types: '{truck,van}',
        has_expiration: true,
        default_validity_days: 180, // 6 mois
        file_format_restrictions: '{"allowed": ["pdf"], "max_size_mb": 5}',
        validation_rules: null,
        is_active: true,
        display_order: 13,
        created_at: this.now(),
        updated_at: this.now(),
      },
      {
        code: 'VISITE_TECHNIQUE_REMORQUE',
        label_fr: 'Visite Technique Remorque',
        label_en: 'Trailer Technical Inspection',
        description: 'Certificat de visite technique de la remorque',
        applicable_to: 'vehicle',
        required_for_roles: null,
        required_for_vehicle_types: '{truck}',
        has_expiration: true,
        default_validity_days: 180, // 6 mois
        file_format_restrictions: '{"allowed": ["pdf"], "max_size_mb": 5}',
        validation_rules: null,
        is_active: true,
        display_order: 14,
        created_at: this.now(),
        updated_at: this.now(),
      },
      {
        code: 'PHOTO_VEHICULE_AVANT',
        label_fr: 'Photo Véhicule - Vue Avant',
        label_en: 'Vehicle Photo - Front View',
        description: 'Photo du véhicule vue de face',
        applicable_to: 'vehicle',
        required_for_roles: null,
        required_for_vehicle_types: '{truck,van,motorcycle,car}',
        has_expiration: false,
        default_validity_days: null,
        file_format_restrictions: '{"allowed": ["jpg", "jpeg", "png"], "max_size_mb": 10}',
        validation_rules: null,
        is_active: true,
        display_order: 15,
        created_at: this.now(),
        updated_at: this.now(),
      },
      {
        code: 'PHOTO_VEHICULE_ARRIERE',
        label_fr: 'Photo Véhicule - Vue Arrière',
        label_en: 'Vehicle Photo - Rear View',
        description: 'Photo du véhicule vue de derrière',
        applicable_to: 'vehicle',
        required_for_roles: null,
        required_for_vehicle_types: '{truck,van,motorcycle,car}',
        has_expiration: false,
        default_validity_days: null,
        file_format_restrictions: '{"allowed": ["jpg", "jpeg", "png"], "max_size_mb": 10}',
        validation_rules: null,
        is_active: true,
        display_order: 16,
        created_at: this.now(),
        updated_at: this.now(),
      },
      {
        code: 'PHOTO_VEHICULE_GAUCHE',
        label_fr: 'Photo Véhicule - Côté Gauche',
        label_en: 'Vehicle Photo - Left Side',
        description: 'Photo du véhicule côté gauche',
        applicable_to: 'vehicle',
        required_for_roles: null,
        required_for_vehicle_types: '{truck,van,motorcycle,car}',
        has_expiration: false,
        default_validity_days: null,
        file_format_restrictions: '{"allowed": ["jpg", "jpeg", "png"], "max_size_mb": 10}',
        validation_rules: null,
        is_active: true,
        display_order: 17,
        created_at: this.now(),
        updated_at: this.now(),
      },
      {
        code: 'PHOTO_VEHICULE_DROIT',
        label_fr: 'Photo Véhicule - Côté Droit',
        label_en: 'Vehicle Photo - Right Side',
        description: 'Photo du véhicule côté droit',
        applicable_to: 'vehicle',
        required_for_roles: null,
        required_for_vehicle_types: '{truck,van,motorcycle,car}',
        has_expiration: false,
        default_validity_days: null,
        file_format_restrictions: '{"allowed": ["jpg", "jpeg", "png"], "max_size_mb": 10}',
        validation_rules: null,
        is_active: true,
        display_order: 18,
        created_at: this.now(),
        updated_at: this.now(),
      },
      {
        code: 'CNI_CHAUFFEUR',
        label_fr: 'CNI du Chauffeur',
        label_en: 'Driver ID Card',
        description: "Carte nationale d'identité du chauffeur",
        applicable_to: 'vehicle',
        required_for_roles: null,
        required_for_vehicle_types: '{truck,van,motorcycle,car}',
        has_expiration: true,
        default_validity_days: 3650, // 10 ans
        file_format_restrictions: '{"allowed": ["pdf", "jpg", "jpeg", "png"], "max_size_mb": 5}',
        validation_rules: null,
        is_active: true,
        display_order: 19,
        created_at: this.now(),
        updated_at: this.now(),
      },
      {
        code: 'PHOTO_CHAUFFEUR',
        label_fr: 'Photo Demi-carte Postale Chauffeur',
        label_en: 'Driver Passport Photo',
        description: 'Photo demi-carte postale du chauffeur',
        applicable_to: 'vehicle',
        required_for_roles: null,
        required_for_vehicle_types: '{truck,van,motorcycle,car}',
        has_expiration: false,
        default_validity_days: null,
        file_format_restrictions: '{"allowed": ["jpg", "jpeg", "png"], "max_size_mb": 5}',
        validation_rules: null,
        is_active: true,
        display_order: 20,
        created_at: this.now(),
        updated_at: this.now(),
      },
    ])
  }

  async down() {
    await this.db.from('document_types').delete()
  }
}
